stages:
  - test

variables:
  SECURITY_SCAN_POLICY: "Secret SCA SAST"
  SECURITY_SCAN_COMPONENT_GROUP: seblap
  CI_DEBUG_TRACE: "false"
  #CODECLIMATE_PREFIX: ""
  #DEFECTDOJO_URL: "https://vt-defectdojo-test.domaintests.loc"
  DEFECTDOJO_PRODUCT_NAME: "seblap_replatforming"
  DEFECTDOJO_COMPONENT_NAME: "seblap_replatforming"

include:
    - project: exfo/innersource/security-tools/securityscans
      ref: master
      file: '/templates/.gitlabcom-scanning.yml'
